name: Update template branch

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org

      - name: Resolve published @canopy-iiif/lib version
        id: ver
        run: |
          echo "VERSION=$(npm view @canopy-iiif/lib version || echo '')" >> $GITHUB_OUTPUT

      - name: Prepare clean template
        env:
          VERSION: ${{ steps.ver.outputs.VERSION }}
        run: |
          rm -rf dist-template
          mkdir -p dist-template
          rsync -a --delete \
            --exclude ".git" \
            --exclude "node_modules" \
            --exclude "AGENTS.md" \
            --exclude "packages" \
            --exclude ".cache" \
            --exclude ".changeset" \
            --exclude ".github/workflows/template.yml" \
            --exclude ".github/workflows/retarget-pr-base.yml" \
            ./ dist-template/

          node -e "const fs=require('fs');const v=process.env.VERSION||'';const p='dist-template/package.json';const j=JSON.parse(fs.readFileSync(p,'utf8'));if(j.dependencies&&j.dependencies['@canopy-iiif/lib']){j.dependencies['@canopy-iiif/lib']=v?('^'+v):'*'}fs.writeFileSync(p,JSON.stringify(j,null,2))"

      - name: Push to template branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd dist-template
          git init -b main
          git config user.name "Mat Jordan"
          git config user.email "mat@northwestern.edu"
          git add .
          git commit -m "Create new template from main"
          git branch -M template
          git remote add origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git"
          git push --force origin template
